In [1]:
import theano 
import os
import matplotlib.pyplot as plt
import numpy as np 
import cv2
from sklearn import preprocessing
from tqdm import tqdm
from tensorflow.keras.utils import to_categorical


In [2]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, MaxPool3D,Flatten
from tensorflow.keras.layers import Conv3D, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping

In [3]:
img_rows,img_cols = 64,64
frame_size = 30
total_class = 3
X_tr=[]
X_val = []

### Pre-Processing for train data

In [4]:
ls_path = os.path.join('./dataset/leapGestRecog/train_data/train/1/')
listing = os.listdir(ls_path)

frames = []
img_depth = 0

for img in tqdm(range(300)):
    for imgs in listing:
        if img_depth <30:
            img = os.path.join(ls_path,imgs)
           # print(img)
            frame = cv2.imread(img)
            frame = cv2.resize(frame,(img_rows,img_cols),interpolation=cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frames.append(gray)
            img_depth = img_depth+1
    
    #else:
        #break
    input_img = np.array(frames)
    ipt = np.rollaxis(np.rollaxis(input_img,2,0),2,0)
    ipt = np.rollaxis(ipt,2,0)
    X_tr.append(ipt)
        
    
print(ipt.shape)
num_samples = len(X_tr)
print(num_samples)

100%|██████████| 300/300 [00:00<00:00, 2315.24it/s]

(30, 64, 64, 3)
300


In [6]:
ls_path_2 = os.path.join('./dataset/leapGestRecog/train_data/train/2/')
listing_2 = os.listdir(ls_path_2)

frames = []
img_depth = 0

for img in tqdm(range(300)):
    for imgs_2 in listing_2:
        if img_depth <30:
            img = os.path.join(ls_path_2,imgs_2)
           # print(img)
            frame = cv2.imread(img)
            frame = cv2.resize(frame,(img_rows,img_cols),interpolation=cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frames.append(gray)
            img_depth = img_depth+1
    
    #else:
        #break
    input_img = np.array(frames)
    ipt = np.rollaxis(np.rollaxis(input_img,2,0),2,0)
    ipt = np.rollaxis(ipt,2,0)
    X_tr.append(ipt)
        
    
print(ipt.shape)
num_samples = len(X_tr)
print(num_samples)

100%|██████████| 300/300 [00:00<00:00, 644.75it/s]

(30, 64, 64, 3)
600


In [7]:
ls_path_3 = os.path.join('./dataset/leapGestRecog/train_data/train/3/')
listing_3 = os.listdir(ls_path_3)

frames = []
img_depth = 0 

for img in tqdm(range(300)):
    for imgs_3 in listing_3:
 
        if img_depth<30:
            img = os.path.join(ls_path_3,imgs_3)
            frame = cv2.imread(img)
            frame = cv2.resize(frame,(img_rows,img_cols),interpolation=cv2.INTER_AREA)
            gray = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
            frames.append(gray)
            img_depth = img_depth+1
    
    input_img = np.array(frames)
    ipt = np.rollaxis(np.rollaxis(input_img,2,0),2,0)
    ipt = np.rollaxis(ipt,2,0)
    X_tr.append(ipt)
    
print(ipt.shape)
num_samples = len(X_tr)
print(num_samples)

100%|██████████| 300/300 [00:00<00:00, 668.53it/s]

(30, 64, 64, 3)
900


### Pre_processing fro val_data

In [8]:
ls_path_val = os.path.join('./dataset/leapGestRecog/train_data/val/1/')
listing_val = os.listdir(ls_path_val)

frames = []
img_depth = 0

for img in tqdm(range(100)):
    for imgs_val in listing_val:
 
        if img_depth <30:
            img = os.path.join(ls_path_val,imgs_val)
           # print(img)
            frame = cv2.imread(img)
            frame = cv2.resize(frame,(img_rows,img_cols),interpolation=cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frames.append(gray)
            img_depth = img_depth+1
    
    #else:
        #break
    input_img = np.array(frames)
    ipt = np.rollaxis(np.rollaxis(input_img,2,0),2,0)
    ipt = np.rollaxis(ipt,2,0)
    X_val.append(ipt)
        
    
print(ipt.shape)
num_samples = len(X_val)
print(num_samples)
    

100%|██████████| 100/100 [00:00<00:00, 226.06it/s]

(30, 64, 64, 3)
100


In [9]:
ls_path_val_2 = os.path.join('./dataset/leapGestRecog/train_data/val/2/')
listing_val_2 = os.listdir(ls_path_val_2)

frames = []
img_depth = 0

for img in tqdm(range(100)):
    for imgs_val_2 in listing_val_2:
        if img_depth <30:
            img = os.path.join(ls_path_val_2,imgs_val_2)
           # print(img)
            frame = cv2.imread(img)
            frame = cv2.resize(frame,(img_rows,img_cols),interpolation=cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frames.append(gray)
            img_depth = img_depth+1
    
    #else:
        #break
    input_img = np.array(frames)
    ipt = np.rollaxis(np.rollaxis(input_img,2,0),2,0)
    ipt = np.rollaxis(ipt,2,0)
    X_val.append(ipt)
        
    
print(ipt.shape)
num_samples = len(X_val)
print(num_samples)
    

100%|██████████| 100/100 [00:00<00:00, 224.74it/s]

(30, 64, 64, 3)
200


In [10]:
ls_path_val_3 = os.path.join('./dataset/leapGestRecog/train_data/val/3/')
listing_val_3 = os.listdir(ls_path_val_3)

frames = []
img_depth = 0

for img in tqdm(range(100)):
    for imgs_val_3 in listing_val_3:
        if img_depth <30:
            img = os.path.join(ls_path_val_3,imgs_val_3)
           # print(img)
            frame = cv2.imread(img)
            frame = cv2.resize(frame,(img_rows,img_cols),interpolation=cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frames.append(gray)
            img_depth = img_depth+1
    
    #else:
        #break
    input_img = np.array(frames)
    ipt = np.rollaxis(np.rollaxis(input_img,2,0),2,0)
    ipt = np.rollaxis(ipt,2,0)
    X_val.append(ipt)
        
    
print(ipt.shape)
num_samples = len(X_val)
print(num_samples)
    

100%|██████████| 100/100 [00:00<00:00, 197.63it/s]

(30, 64, 64, 3)
300


In [11]:
X_tr_array = np.array(X_tr) #convert the frames read to array
num_samples = len(X_tr_array)
print('Total training samples:',num_samples)
X_val_array = np.array(X_val)
num_val_samples = len(X_val_array)
print('Total validation samples:', num_val_samples)

Total training samples: 900
Total validation samples: 300


In [12]:
label_train = np.ones((num_samples),dtype=int)
label_train[0:300] = 0
label_train[300:600] = 1
label_train[600:900] = 2
label_val = np.ones((num_val_samples),dtype=int)
label_val[0:100] = 0
label_val[100:200] = 1
label_val[200:300] = 2

In [13]:
train_data = [X_tr_array,label_train]

In [33]:
(X_train,y_train) = (train_data[0],train_data[1])
print('Training data shape:',X_train.shape)

Training data shape: (900, 30, 64, 64, 3)


In [34]:
train_set = np.zeros((900,30,64,64,3),'float32')

In [35]:
for h in range(300):
    train_set[h][:][:][:][:]=X_train[h,:,:,:]

In [36]:
val_data = [X_val_array,label_val]

In [37]:
(X_val,y_val) = (val_data[0],val_data[1])
print('Validtion data shape:', X_val.shape)

Validtion data shape: (300, 30, 64, 64, 3)


In [38]:
val_set = np.zeros((300,30,64,64,3),'float32')

In [39]:
for h in range(300):
    val_set[h][:][:][:] = X_val[h,:,:,:]

In [40]:
nb_classes = 3
Y_train = to_categorical(y_train,nb_classes)

In [41]:
Y_val = to_categorical(y_val,nb_classes)

In [42]:
train_set = train_set.astype('float32')
train_set-=np.mean(train_set)
print("Mean Train:",train_set)
train_set /=np.max(train_set)
print("Max Train", train_set)

Mean Train: [[[[[-4.2400913  -4.2400913  -4.2400913 ]
    [-3.2400913  -3.2400913  -3.2400913 ]
    [-3.2400913  -3.2400913  -3.2400913 ]
    ...
    [-5.2400913  -5.2400913  -5.2400913 ]
    [-5.2400913  -5.2400913  -5.2400913 ]
    [-5.2400913  -5.2400913  -5.2400913 ]]

   [[-4.2400913  -4.2400913  -4.2400913 ]
    [-3.2400913  -3.2400913  -3.2400913 ]
    [-3.2400913  -3.2400913  -3.2400913 ]
    ...
    [-5.2400913  -5.2400913  -5.2400913 ]
    [-5.2400913  -5.2400913  -5.2400913 ]
    [-5.2400913  -5.2400913  -5.2400913 ]]

   [[-3.2400913  -3.2400913  -3.2400913 ]
    [-3.2400913  -3.2400913  -3.2400913 ]
    [-2.2400913  -2.2400913  -2.2400913 ]
    ...
    [-5.2400913  -5.2400913  -5.2400913 ]
    [-5.2400913  -5.2400913  -5.2400913 ]
    [-5.2400913  -5.2400913  -5.2400913 ]]

   ...

   [[-1.2400913  -1.2400913  -1.2400913 ]
    [-0.24009132 -0.24009132 -0.24009132]
    [ 0.7599087   0.7599087   0.7599087 ]
    ...
    [-4.2400913  -4.2400913  -4.2400913 ]
    [-5.2400913  -

Max Train [[[[[-0.01753844 -0.01753844 -0.01753844]
    [-0.0134021  -0.0134021  -0.0134021 ]
    [-0.0134021  -0.0134021  -0.0134021 ]
    ...
    [-0.02167477 -0.02167477 -0.02167477]
    [-0.02167477 -0.02167477 -0.02167477]
    [-0.02167477 -0.02167477 -0.02167477]]

   [[-0.01753844 -0.01753844 -0.01753844]
    [-0.0134021  -0.0134021  -0.0134021 ]
    [-0.0134021  -0.0134021  -0.0134021 ]
    ...
    [-0.02167477 -0.02167477 -0.02167477]
    [-0.02167477 -0.02167477 -0.02167477]
    [-0.02167477 -0.02167477 -0.02167477]]

   [[-0.0134021  -0.0134021  -0.0134021 ]
    [-0.0134021  -0.0134021  -0.0134021 ]
    [-0.00926577 -0.00926577 -0.00926577]
    ...
    [-0.02167477 -0.02167477 -0.02167477]
    [-0.02167477 -0.02167477 -0.02167477]
    [-0.02167477 -0.02167477 -0.02167477]]

   ...

   [[-0.00512943 -0.00512943 -0.00512943]
    [-0.0009931  -0.0009931  -0.0009931 ]
    [ 0.00314324  0.00314324  0.00314324]
    ...
    [-0.01753844 -0.01753844 -0.01753844]
    [-0.02167477 -0.

In [43]:
val_set = val_set.astype('float32')
print(np.mean(val_set))
val_set -=np.mean(val_set)
print(np.max(val_set))
val_set /=np.max(val_set)

31.302109
219.69789


In [44]:
def build_model():
    model = Sequential()

    model.add(Conv3D(8, (3,3,3), input_shape=(frame_size,img_cols,img_rows,3),activation='relu'))
    model.add(Conv3D(16, (3,3,3),activation='relu'))
    # model.add(BatchNormalization())
    model.add(MaxPool3D())
    # model.add(Dropout(0.25))

    model.add(Conv3D(32, (3,3,3),activation='relu'))
    model.add(Conv3D(64, (3,3,3),activation='relu'))
    model.add(BatchNormalization())
    model.add(MaxPool3D())
    model.add(Dropout(0.25))

    model.add(Flatten())

    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))

    model.add(Dense(1024, activation='relu'))
    model.add(Dropout(0.5))

    model.add(Dense(nb_classes, activation='softmax'))

    return model
    
    

In [45]:
model = build_model()

In [46]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv3d_4 (Conv3D)            (None, 28, 62, 62, 8)     656       
_________________________________________________________________
conv3d_5 (Conv3D)            (None, 26, 60, 60, 16)    3472      
_________________________________________________________________
max_pooling3d_2 (MaxPooling3 (None, 13, 30, 30, 16)    0         
_________________________________________________________________
conv3d_6 (Conv3D)            (None, 11, 28, 28, 32)    13856     
_________________________________________________________________
conv3d_7 (Conv3D)            (None, 9, 26, 26, 64)     55360     
_________________________________________________________________
batch_normalization_1 (Batch (None, 9, 26, 26, 64)     256       
_________________________________________________________________
max_pooling3d_3 (MaxPooling3 (None, 4, 13, 13, 64)    

In [47]:
save_dir = os.path.join(os.getcwd(),'saved_model')
print(os.getcwd())
model_name = 'LeapGesRecog'
if not os.path.isdir(save_dir):
    os.makedirs(save_dir)
model_path = os.path.join(save_dir,model_name)
checkpoint = ModelCheckpoint(model_path,monitor='val_acc',save_best_only=True,verbose=1)
earlystop = EarlyStopping(monitor='val_loss',patience=50,verbose=1)


/media/labina/project/Research/leapgesturerecog


In [48]:
model.compile(optimizer ='RMSprop',
              loss = 'categorical_crossentropy',
                metrics = ['acc'])

In [49]:
batch_size = 32
epoch = 50
lr_reducer = ReduceLROnPlateau(monitor='val_loss',factor=0.05,
                              cooldowm=0,patience=10,min_lr=0.005/(2^4),verbose=1)

In [50]:
history = model.fit(train_set,Y_train,
                  validation_data=(val_set,Y_val),
                  batch_size=batch_size,
                  epochs=epoch,
                  callbacks=[checkpoint,lr_reducer])

Train on 900 samples, validate on 300 samples
Epoch 1/50
896/900 [============================>.] - ETA: 1s - loss: 46.4219 - acc: 0.5982 
Epoch 00001: val_acc improved from -inf to 0.33333, saving model to /media/labina/project/Research/leapgesturerecog/saved_model/LeapGesRecog
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: /media/labina/project/Research/leapgesturerecog/saved_model/LeapGesRecog/assets
900/900 [==============================] - 343s 381ms/sample - loss: 46.2171 - acc: 0.5989 - val_loss: 28.4751 - val_acc: 0.3333
Epoch 2/50
896/900 [============================>.] - ETA: 1s - loss: 0.8462 - acc: 0.6730 
Epoch 00002: val_acc did not improve from 0.33333
900/900 [==============================] - 327s 364ms/sample - loss: 0.8448 - acc: 0.6722 - val_loss: 19.6688 - val_acc: 0.3333
Epoch 3/50
896/900 [============================>.] - ETA: 1s - loss: 0.5620 - acc: 0.6775 
Epoch 00003: val_acc did not impr

Epoch 28/50
896/900 [============================>.] - ETA: 1s - loss: 0.4671 - acc: 0.6607 
Epoch 00028: val_acc did not improve from 0.66667
900/900 [==============================] - 316s 352ms/sample - loss: 0.4674 - acc: 0.6600 - val_loss: 73.1697 - val_acc: 0.3333
Epoch 29/50
896/900 [============================>.] - ETA: 1s - loss: 0.6278 - acc: 0.6540 
Epoch 00029: val_acc did not improve from 0.66667
900/900 [==============================] - 313s 348ms/sample - loss: 0.6264 - acc: 0.6544 - val_loss: 45.7872 - val_acc: 0.3333
Epoch 30/50
896/900 [============================>.] - ETA: 1s - loss: 0.4896 - acc: 0.6462 
Epoch 00030: val_acc did not improve from 0.66667
900/900 [==============================] - 318s 353ms/sample - loss: 0.4897 - acc: 0.6467 - val_loss: 20.5079 - val_acc: 0.3333
Epoch 31/50
896/900 [============================>.] - ETA: 1s - loss: 0.4688 - acc: 0.6708 
Epoch 00031: val_acc did not improve from 0.66667
900/900 [==============================] - 3